version: "3.1"
services:
  mysql:
    image: mysql:8.0
    container_name: teste-php-mysql
    working_dir: /application
    volumes:
      - ./laravel-framework:/application
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=teste-php
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - "8082:3306"

  webserver:
    image: nginx:alpine
    container_name: teste-php-webserver
    working_dir: /application
    volumes:
      - ./laravel-framework:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: phpdocker/php-fpm
    container_name: teste-php-php-fpm
    working_dir: /application
    volumes:
      - ./laravel-framework:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: teste-php-swagger-ui
    environment:
      - SWAGGER_JSON=/app/swagger.yml
    volumes:
      - ./:/app
    ports:
      - "9000:8080"

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: teste-php-swagger-editor
    environment:
      - SWAGGER_JSON=/app/swagger.yml
    volumes:
      - ./:/app
    ports:
      - "9001:8080"
